[package]
name = "shizuka-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.0"
env_logger = "0.11.5"
tokio = { version = "1.24.2", features = ["full"]}
reqwest = {version = "0.12.5", features = ["json"]}
serde = { version = "1.0.152", features = ["derive"]}
chrono = "0.4.23"